# Generated by Django 4.2.1 on 2023-05-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appTubesPI", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
