# Generated by Django 4.2.1 on 2023-05-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appTubesPI", "0002_alter_user_email_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="list_toko",
            name="jam_operasional",
        ),
        migrations.AddField(
            model_name="list_toko",
            name="jamBuka_operasional",
            field=models.TimeField(default="00:00:00"),
        ),
        migrations.AddField(
            model_name="list_toko",
            name="jamTutup_operasional",
            field=models.TimeField(default="00:00:00"),
        ),
        migrations.AlterField(
            model_name="kain",
            name="desc",
            field=models.TextField(max_length=299),
        ),
        migrations.AlterField(
            model_name="kain",
            name="highest_est",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="kain",
            name="lowest_est",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="kain",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
